# Mapeo de nombres de activos entre brokers y Yahoo Finance
# Formato: nombre_broker: ticker_yahoo

# Bonos
AL30: AL30.BA
AL29: AL29.BA
GD30: GD30.BA
GD29: GD29.BA

# Acciones Argentinas
GGAL: GGAL.BA
YPF: YPF.BA
PAMP: PAMP.BA
VIST: VIST.BA
ALUA: ALUA.BA
BMA: BMA.BA
CRES: CRES.BA
EDN: EDN.BA
LOMA: LOMA.BA
MIRG: MIRG.BA
SUPV: SUPV.BA
TGSU2: TGSU2.BA
TXAR: TXAR.BA
VALO: VALO.BA

# ADRs (Trading en NYSE)
GGAL_ADR: GGAL
YPF_ADR: YPF
BMA_ADR: BMA
CRESY: CRESY
EDN_ADR: EDN
LOMA_ADR: LOMA
SUPV_ADR: SUPV
TGS: TGS
VISTA: VIST

# CEDEARs
AAPL: AAPL
GOOGL: GOOGL
MSFT: MSFT
TSLA: TSLA
AMZN: AMZN
META: META
NVDA: NVDA
KO: KO
WMT: WMT
DIS: DIS

# √çndices
MERVAL: ^MERV
SPY: SPY
QQQ: QQQ

# Divisas
USDARS: USDARS=X
